### ISSUE TITLE
Request for the localization of a couple of strings

### ISSUE THREAD

**Issue by valadzhov** [IgniteUI/igniteui-angular-api-i18n#6]
Can we get the following strings localized?
constructor
any
memberof
Default value
Static

**Comment by Aleksandyr** [comment]
@valadjov 
Those two: 
**constructor**
**any**
are not possible to be localized because they are a keywords into the source code and it's not "politically" right.
**memberof** -> already localized.
**Default value** -> localized. Here is the [PR](https://github.com/IgniteUI/typedoc-plugin-localization/pull/26)
Those two were added by me in addition:
**Rest**
![image](https://user-images.githubusercontent.com/7037740/49276816-3e22d580-f488-11e8-98cb-36ee53ebf165.png)
**Optional**
![image](https://user-images.githubusercontent.com/7037740/49276839-4d098800-f488-11e8-9210-e36d3146ec02.png)
I could find where **Static** stays?
